pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
            git branch: 'main' , url : ''
        }
        }
        stage('Build and Unit testing'){
            steps{
                sh 'mvn clean install'
            }
        }
    }
}
       
